server:
  port: 9000

hikaricp:
  configurationFile: application.yml
spring:
  application:
    name: springBootChapter1
  profiles:
    active: @myActivateFile@,common-@myActivateFile@,mq-@myActivateFile@,redis-@myActivateFile@

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP
      idle-timeout: 30000
      max-lifetime: 30000
      connection-timeout: 1800000
      minimum-idle: 10
      maximum-pool-size: 100
      connection-test-query: SELECT 1

  redis:
    timeout: 5000
    commandTimeout: 5000
    jedis:
      pool:
        max-active: 200
        min-idle: 0
        max-idle: 5
        max-wait: -1

thread:
  pool:
    corePoolSize: 50
    maxPoolSize: 100
    queueSize: 30
    keepAlive: 60
logging:
  config: logback.xml
